set(MD_NETEQ_SOURCES
  ${MD_WEBRTC_SOURCE}/api/audio/audio_frame.cc
  ${MD_WEBRTC_SOURCE}/api/audio/channel_layout.cc
  ${MD_WEBRTC_SOURCE}/api/audio_codecs/audio_decoder.cc
  ${MD_WEBRTC_SOURCE}/api/audio_codecs/audio_format.cc
  ${MD_WEBRTC_SOURCE}/api/audio_codecs/opus/audio_decoder_opus.cc
  ${MD_WEBRTC_SOURCE}/api/environment/deprecated_global_field_trials.cc
  ${MD_WEBRTC_SOURCE}/api/environment/environment_factory.cc
  ${MD_WEBRTC_SOURCE}/api/environment/force_test_environment.cc
  ${MD_WEBRTC_SOURCE}/api/field_trials.cc
  ${MD_WEBRTC_SOURCE}/api/field_trials_registry.cc
  ${MD_WEBRTC_SOURCE}/api/neteq/default_neteq_controller_factory.cc
  ${MD_WEBRTC_SOURCE}/api/neteq/default_neteq_factory.cc
  ${MD_WEBRTC_SOURCE}/api/neteq/neteq.cc
  ${MD_WEBRTC_SOURCE}/api/neteq/tick_timer.cc
  ${MD_WEBRTC_SOURCE}/api/rtc_event_log/rtc_event_log.cc
  ${MD_WEBRTC_SOURCE}/api/rtp_headers.cc
  ${MD_WEBRTC_SOURCE}/api/rtp_packet_info.cc
  ${MD_WEBRTC_SOURCE}/api/task_queue/task_queue_base.cc
  ${MD_WEBRTC_SOURCE}/api/units/data_rate.cc
  ${MD_WEBRTC_SOURCE}/api/units/data_size.cc
  ${MD_WEBRTC_SOURCE}/api/units/frequency.cc
  ${MD_WEBRTC_SOURCE}/api/units/time_delta.cc
  ${MD_WEBRTC_SOURCE}/api/units/timestamp.cc
  ${MD_WEBRTC_SOURCE}/api/video/color_space.cc
  ${MD_WEBRTC_SOURCE}/common_audio/audio_util.cc
  ${MD_WEBRTC_SOURCE}/common_audio/resampler/resampler.cc
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/auto_corr_to_refl_coef.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/auto_correlation.cc
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/copy_set_operations.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/cross_correlation.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/division_operations.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/dot_product_with_scale.cc
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/downsample_fast.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/energy.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/filter_ar.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/filter_ar_fast_q12.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/filter_ma_fast_q12.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/get_hanning_window.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/get_scaling_square.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/levinson_durbin.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/lpc_to_refl_coef.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/min_max_operations.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/randomization_functions.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/refl_coef_to_lpc.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/resample.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/resample_48khz.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/resample_by_2.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/resample_by_2_internal.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/resample_fractional.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/spl_init.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/spl_inl.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/spl_sqrt.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/splitting_filter.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/vector_operations.c
  ${MD_WEBRTC_SOURCE}/common_audio/signal_processing/vector_scaling_operations.c
  ${MD_WEBRTC_SOURCE}/common_audio/third_party/ooura/fft_size_128/ooura_fft.cc
  ${MD_WEBRTC_SOURCE}/common_audio/third_party/ooura/fft_size_256/fft4g.cc
  ${MD_WEBRTC_SOURCE}/common_audio/third_party/spl_sqrt_floor/spl_sqrt_floor.c
  ${MD_WEBRTC_SOURCE}/common_audio/vad/vad_core.c
  ${MD_WEBRTC_SOURCE}/common_audio/vad/vad_filterbank.c
  ${MD_WEBRTC_SOURCE}/common_audio/vad/vad_gmm.c
  ${MD_WEBRTC_SOURCE}/common_audio/vad/vad_sp.c
  ${MD_WEBRTC_SOURCE}/common_audio/vad/webrtc_vad.c
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/codecs/cng/webrtc_cng.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/codecs/opus/audio_coder_opus_common.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/codecs/opus/audio_decoder_opus.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/codecs/opus/opus_interface.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/accelerate.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/audio_multi_vector.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/audio_vector.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/background_noise.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/buffer_level_filter.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/comfort_noise.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/cross_correlation.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/decision_logic.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/decoder_database.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/delay_constraints.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/delay_manager.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/dsp_helper.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/dtmf_buffer.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/dtmf_tone_generator.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/expand.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/expand_uma_logger.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/histogram.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/merge.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/neteq_impl.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/normal.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/packet.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/packet_arrival_history.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/packet_buffer.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/preemptive_expand.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/random_vector.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/red_payload_splitter.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/reorder_optimizer.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/statistics_calculator.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/sync_buffer.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/time_stretch.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/timestamp_scaler.cc
  ${MD_WEBRTC_SOURCE}/modules/audio_coding/neteq/underrun_optimizer.cc
  ${MD_WEBRTC_SOURCE}/rtc_base/checks.cc
  ${MD_WEBRTC_SOURCE}/rtc_base/event.cc
  ${MD_WEBRTC_SOURCE}/rtc_base/event_tracer.cc
  ${MD_WEBRTC_SOURCE}/rtc_base/experiments/field_trial_list.cc
  ${MD_WEBRTC_SOURCE}/rtc_base/experiments/field_trial_parser.cc
  ${MD_WEBRTC_SOURCE}/rtc_base/experiments/field_trial_units.cc
  ${MD_WEBRTC_SOURCE}/rtc_base/experiments/struct_parameters_parser.cc
  ${MD_WEBRTC_SOURCE}/rtc_base/logging.cc
  ${MD_WEBRTC_SOURCE}/rtc_base/memory/aligned_malloc.cc
  ${MD_WEBRTC_SOURCE}/rtc_base/numerics/exp_filter.cc
  ${MD_WEBRTC_SOURCE}/rtc_base/platform_thread.cc
  ${MD_WEBRTC_SOURCE}/rtc_base/platform_thread_types.cc
  ${MD_WEBRTC_SOURCE}/rtc_base/ref_counter.cc
  ${MD_WEBRTC_SOURCE}/rtc_base/string_encode.cc
  ${MD_WEBRTC_SOURCE}/rtc_base/string_utils.cc
  ${MD_WEBRTC_SOURCE}/rtc_base/strings/string_builder.cc
  ${MD_WEBRTC_SOURCE}/rtc_base/synchronization/sequence_checker_internal.cc
  ${MD_WEBRTC_SOURCE}/rtc_base/synchronization/yield.cc
  ${MD_WEBRTC_SOURCE}/rtc_base/synchronization/yield_policy.cc
  ${MD_WEBRTC_SOURCE}/rtc_base/system/system_time.cc
  ${MD_WEBRTC_SOURCE}/rtc_base/system_time.cc
  ${MD_WEBRTC_SOURCE}/rtc_base/time_utils.cc
  ${MD_WEBRTC_SOURCE}/system_wrappers/source/clock.cc
  ${MD_WEBRTC_SOURCE}/system_wrappers/source/metrics.cc
  ${MD_WEBRTC_SOURCE}/modules/rtp_rtcp/source/rtp_header_extensions.cc
  ${MD_WEBRTC_SOURCE}/modules/rtp_rtcp/source/rtp_packet.cc
  ${MD_WEBRTC_SOURCE}/modules/rtp_rtcp/source/rtp_header_extension_map.cc
  ${MD_WEBRTC_SOURCE}/rtc_base/copy_on_write_buffer.cc
  ${MD_WEBRTC_SOURCE}/api/video/hdr_metadata.cc
  ${MD_WEBRTC_SOURCE}/api/video/video_timing.cc
  ${MD_WEBRTC_SOURCE}/api/video/video_content_type.cc
  ${MD_WEBRTC_SOURCE}/rtc_base/string_to_number.cc
)
